config/routes.rb
Eerstelijns::Application.routes.draw do
  resources :practices
  resources :visits, except: [:index, :show]
  resources :activities

  root :to => 'practices#index'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :animal_activities
  has_many :animals, :through => :animal_activities
  attr_accessible :animal_id, :name, :price
end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :practice
  attr_accessible :practice_id, :street, :street_number, :zip_code , :town
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :visit
  has_many :animal_activities
  has_many :activities, :through => :animal_activities
  attr_accessible :name, :specie, :visit_id, :activities_attributes
end

app/models/animal_activity.rb
class AnimalActivity < ActiveRecord::Base
  belongs_to :animal
  belongs_to :activity
  attr_accessible :activity_id, :animal_id, :created_at
  
end

app/models/practice.rb
class Practice < ActiveRecord::Base
  has_one :address, :dependent => :destroy
  has_many :visits, :dependent => :destroy
  accepts_nested_attributes_for :visits, :allow_destroy => true
  accepts_nested_attributes_for :address, :allow_destroy => true
  attr_accessible :name, :visits_attributes, :address_attributes
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :practice
  has_many :animals, :dependent => :destroy
  accepts_nested_attributes_for :animals, :allow_destroy => true
  attr_accessible :date, :practice_id, :animals_attributes
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  def index
    @activities = Activity.all
  end

  def show
    @activity = Activity.find(params[:id])
  end

def new
  @activity = Activity.new
end

def create
  @activity = Activity.new(params[:activity])
  if @activity.save
    redirect_to @activity, :notice => "Successfully created activity."
  else
    render :action => 'new'
  end
end





def edit
  @activity = Activity.find(params[:id])
  
end

def update
  @activity = Activity.find(params[:id])
  if @activity.update_attributes(params[:activity])
    redirect_to @activity, :notice  => "Successfully updated visit."
  else
    render :action => 'edit'
  end
end

def destroy
  @activity = Activity.find(params[:id])
  @activity.destroy
  redirect_to activity_url, :notice => "Successfully destroyed activity."
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  def index
    @practices = Practice.all
  end

  def show
    @practice = Practice.find(params[:id])
  end

  def new
    @practice = Practice.new 
    @practice.build_address

  end

  def create
    @practice = Practice.new(params[:practice])
    if @practice.save
      redirect_to @practice, :notice => "Successfully created practice."
    else
      render :action => 'new'
    end
  end

  def edit
    @practice = Practice.find(params[:id])
  end

  def update
    @practice = Practice.find(params[:id])
    if @practice.update_attributes(params[:practice])
      redirect_to @practice, :notice  => "Successfully updated practice."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @practice = Practice.find(params[:id])
    @practice.destroy
    redirect_to practices_url, :notice => "Successfully destroyed practice."
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def new
    @visit = Visit.new
    @visit.animals.build 
    @visit.date ||= Date.today
  end

  def create
    @visit = Visit.new(params[:visit])
    if @visit.save
      redirect_to practice_path(:id => @visit.practice_id), :notice => "Successfully created visit."
    else
      render :action => 'new'
    end
  end

  def edit
    @visit = Visit.find(params[:id])
    @visit.date ||= Date.today
  end

  def update
    @visit = Visit.find(params[:id])
    if @visit.update_attributes(params[:visit])
      redirect_to @visit, :notice  => "Successfully updated visit."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy
    redirect_to visits_url, :notice => "Successfully destroyed visit."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end

  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/activities/_form.html.haml
= semantic_form_for @activity do |f|
  = f.inputs
  = f.actions

app/views/activities/edit.html.haml
- title "Edit Onderzoek"
= render 'form'
%p
  = link_to "Show", @activity
  
  = link_to "View All", activities_path

app/views/activities/index.html.haml
- title "Lijst Onderzoeken"
%table
  %tr
    %th Naam onderzoek
    %th Prijs
  
  - for activity in @activities
    %tr
      %td= activity.name
      %td= activity.price
      %td= link_to "Show", activity
      %td= link_to "Edit", edit_activity_path(activity)
      %td= link_to "Destroy", activity, :confirm => 'Are you sure?', :method => :delete
%p= link_to "Nieuw onderzoek toevoegen", new_activity_path

app/views/activities/new.html.haml
- title "Nieuw onderzoek toevoegen"
= render 'form'

%p= link_to "Back to List", activities_path

app/views/activities/show.html.haml
- title "Onderzoek"
%p
  %strong Naam onderzoek:
  = @activity.name
  %br
  %strong Prijs
  = @activity.price
  %br
  %br
  
%p
  = link_to "Edit", edit_activity_path(@activity)
  = link_to "Destroy", @activity, :confirm => 'Are you sure?', :method => :delete
  = link_to "View All", activities_path

app/views/layouts/application.html.haml
!!! 
%html
  %head
    %title= h(yield(:title) || "Untitled")
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = yield(:head)
  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"
      = link_to "Alle praktijken", practices_path
      = link_to "Nieuwe Praktijk", new_practice_path
      = link_to "Nieuwe bezoeken toevoegen", new_visit_path
      - if show_title?
        %h1= h yield(:title)
        
      = yield

app/views/practices/_address_fields.html.haml
= f.label :street, "Straatnaam"
= f.text_field :street
%br
= f.label :street_number, "Huisnummer"
= f.text_field :street_number
%br
= f.label :zip_code, "Postcode"
= f.text_field :zip_code
%br
= f.label :town, "Woonplaats"
= f.text_field :town

app/views/practices/_animal_fields.html.haml
%p.fields
  = f.label :name, "Naam dier"
  = f.text_field :name
  = f.label :specie, "Diersoort"
  = f.select :specie, options_for_select([ "Hond", "Kat", "Konijn", "Cavia", "Fret", "Anders"])
  = link_to_remove_fields "Verwijder", f
  
  
  
  

app/views/practices/_form.html.haml
= form_for @practice do |f|
  = f.error_messages
  %p
    = f.label :name, "Naam Praktijk"
    %br
    = f.text_field :name
  %strong Adres: 
  %br   
  = f.fields_for :address do |address|
    = render 'address_fields', :f => address
    
  = f.fields_for :visits do |visit|
    = render 'visit_fields', :f => visit
  = link_to_add_fields "Voeg bezoek toe", f, :visits
  %p= f.submit



  

app/views/practices/_visit_fields.html.haml
.fields
  %p
    = f.label :date, "Datum bezoek"
    = link_to_remove_fields "Verwijder", f 
    %br
    = f.date_select :date
    
    
    
  = f.fields_for :animals do |animal|
    = render 'animal_fields', :f => animal
    
  = link_to_add_fields "Voeg dier toe", f, :animals

app/views/practices/edit.html.haml
- title "Edit Practice"
= render 'form'
%p
  = link_to "Show", @practice
  
  = link_to "View All", practices_path

app/views/practices/index.html.haml
- title "Praktijken"
%table
  %tr
    %th Naam praktijk
  
  - for practice in @practices
    %tr
      %td= practice.name
      %td= link_to "Show", practice
      %td= link_to "Edit", edit_practice_path(practice)
      %td= link_to "Destroy", practice, :confirm => 'Are you sure?', :method => :delete
%p= link_to "New Practice", new_practice_path

app/views/practices/new.html.haml
- title "Nieuwe praktijk toevoegen"
= render 'form'
%p= link_to "Back to List", practices_path

app/views/practices/show.html.haml
- title "Practice"
%p
  %strong Naam praktijk:
  = @practice.name
  %br
  %br
  
  -for visit in @practice.visits
    %strong Datum bezoek:
    = visit.date
    %br
    
    - for animal in visit.animals
      %strong Naam Dier
      = animal.name
      %strong Diersoort
      = animal.specie 
      %br
    %br
  
%p
  = link_to "Edit", edit_practice_path(@practice)
  = link_to "Destroy", @practice, :confirm => 'Are you sure?', :method => :delete
  = link_to "View All", practices_path

app/views/visits/_form.html.haml
= semantic_nested_form_for @visit do |f|
  = f.inputs do
    = f.input :practice, :include_blank => false
    = f.input :date
    
    = f.fields_for :animals do |animal| 
      = animal.label :name, "Naam dier"
      = animal.text_field :name
      = animal.label :specie, "Diersoort"
      = animal.select :specie, options_for_select([ "Hond", "Kat", "Konijn", "Cavia", "Fret", "Anders"])
      = animal.link_to_remove "Verwijder dier" 
     
    %p 
    = f.link_to_add "Add an animal", :animals 
  
  = f.actions 
  

app/views/visits/new.html.haml
- title "Nieuw bezoek toevoegen"
= render 'form'

%p= link_to "Back to List", practices_path